# NumPy


In [2]:
import numpy as np

In [3]:
my_arr = np.arange(1000000)

my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 26.5 ms, sys: 19.3 ms, total: 45.8 ms
Wall time: 58.3 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 805 ms, sys: 249 ms, total: 1.05 s
Wall time: 1.12 s


### Creating ndarrays

In [6]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [7]:
arr2 = np.array(data2)

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.arange(15)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Datatypes for ndarrays

In [15]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [16]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [17]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

### Boolean Indexing

In [18]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [19]:
data = np.random.randn(7,4)

In [20]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [21]:
data

array([[-0.55154366, -0.52408904, -0.8691962 ,  0.92440421],
       [ 2.44814239, -1.07146598, -0.4971869 ,  0.18966932],
       [-0.33417909,  0.21267055,  1.40757252, -2.01277865],
       [ 0.91902986,  0.56182722,  0.30364179,  0.54233015],
       [ 1.25015499, -0.73934842, -1.11472073, -1.01691883],
       [-1.22102112, -1.59105262, -0.24175975, -0.84097235],
       [ 1.8310234 , -0.83012849,  0.25623919, -2.51547846]])

In [22]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [23]:
data[names == "Bob"]

array([[-0.55154366, -0.52408904, -0.8691962 ,  0.92440421],
       [ 0.91902986,  0.56182722,  0.30364179,  0.54233015]])

In [24]:
data[names == "Bob", 2:]

array([[-0.8691962 ,  0.92440421],
       [ 0.30364179,  0.54233015]])

In [25]:
data[names == "Bob", 3]

array([0.92440421, 0.54233015])

Negating a condition by using **~**

In [26]:
data[~(names == "Bob")]

array([[ 2.44814239, -1.07146598, -0.4971869 ,  0.18966932],
       [-0.33417909,  0.21267055,  1.40757252, -2.01277865],
       [ 1.25015499, -0.73934842, -1.11472073, -1.01691883],
       [-1.22102112, -1.59105262, -0.24175975, -0.84097235],
       [ 1.8310234 , -0.83012849,  0.25623919, -2.51547846]])

Selecting two of the three names to combine multiple boolean conditions, use boolean arithmetic operators like **& (and)** and **| (or)**

In [27]:
mask = (names == "Bob") | (names == "Will")

In [29]:
data[mask]

array([[-0.55154366, -0.52408904, -0.8691962 ,  0.92440421],
       [-0.33417909,  0.21267055,  1.40757252, -2.01277865],
       [ 0.91902986,  0.56182722,  0.30364179,  0.54233015],
       [ 1.25015499, -0.73934842, -1.11472073, -1.01691883]])

In [31]:
arr = np.empty((8,4))

In [34]:
for i in range(8):
    arr[i] = [i]
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

### Transposing Arrays and Swaping Axes

In [36]:
arr = np.arange(15).reshape((3,5))

In [37]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Universal Functions: Fast Elements-Wise Array Functions

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [42]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [43]:
x = np.random.randn(8)

y = np.random.randn(8)

In [44]:
x

array([-0.5109964 ,  0.41599417,  0.15551946, -0.21043784,  0.8160163 ,
       -0.21279311, -0.42759633, -0.69023158])

In [45]:
y

array([-0.0244381 ,  0.89307717,  2.11307363, -0.78141466, -0.94686881,
        0.18520666,  0.16590637,  0.32902046])

In [46]:
np.maximum(x,y)

array([-0.0244381 ,  0.89307717,  2.11307363, -0.21043784,  0.8160163 ,
        0.18520666,  0.16590637,  0.32902046])

In [47]:
points = np.arange(-5, 5, 0.01)

In [51]:
xs, ys = np.meshgrid(points, points)

In [52]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [53]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [54]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

### Expressing Conditional Logic as Array Operations

In [55]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])

In [56]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [57]:
arr = np.random.randn(4,4)

In [58]:
arr

array([[ 0.98261489, -1.26033692,  0.52611479, -0.72796231],
       [-0.52453272, -0.41681955,  0.20866421,  0.06317215],
       [ 0.56663536, -1.42888158, -0.20856032,  0.98948222],
       [-0.11365413, -0.42516417, -0.70645726, -0.11342193]])

In [59]:
arr > 0

array([[ True, False,  True, False],
       [False, False,  True,  True],
       [ True, False, False,  True],
       [False, False, False, False]])

In [60]:
np.where(arr > 0, 2, -2)

array([[ 2, -2,  2, -2],
       [-2, -2,  2,  2],
       [ 2, -2, -2,  2],
       [-2, -2, -2, -2]])

Scalars and arrays can be combined when using np.where

In [61]:
np.where(arr > 0, 2, arr)

array([[ 2.        , -1.26033692,  2.        , -0.72796231],
       [-0.52453272, -0.41681955,  2.        ,  2.        ],
       [ 2.        , -1.42888158, -0.20856032,  2.        ],
       [-0.11365413, -0.42516417, -0.70645726, -0.11342193]])

### Linear Algebra

In [62]:
from numpy.linalg import inv, qr

In [63]:
X = np.random.randn(5,5)

In [64]:
mat = X.T.dot(X)

In [65]:
mat

array([[ 7.2582103 ,  1.17885334, -1.65654003, -1.10729161,  0.46660976],
       [ 1.17885334,  2.55516831,  0.01242417,  0.23358498, -1.2174681 ],
       [-1.65654003,  0.01242417,  5.76753696,  0.58912954,  1.41904255],
       [-1.10729161,  0.23358498,  0.58912954,  0.62209518, -1.85079123],
       [ 0.46660976, -1.2174681 ,  1.41904255, -1.85079123, 10.16481085]])

In [66]:
inv(mat)

array([[ 0.41869024, -0.21162635, -0.17062708,  2.0173829 ,  0.34657491],
       [-0.21162635,  0.52332612,  0.06617941, -0.97743528, -0.11481377],
       [-0.17062708,  0.06617941,  0.39835578, -1.79874952, -0.36736601],
       [ 2.0173829 , -0.97743528, -1.79874952, 16.12917242,  2.97820654],
       [ 0.34657491, -0.11481377, -0.36736601,  2.97820654,  0.66226999]])

In [67]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  3.32634361e-17, -2.22764809e-16,
        -2.16767932e-15, -4.36329378e-17],
       [ 4.78414769e-17,  1.00000000e+00,  9.76149928e-17,
        -1.22649333e-15, -2.23917996e-16],
       [ 1.96674686e-17, -1.51241558e-16,  1.00000000e+00,
         1.49565237e-15,  3.30034538e-16],
       [ 3.88373531e-17, -1.56591592e-17,  1.05455694e-17,
         1.00000000e+00, -4.19998051e-17],
       [ 1.79761657e-16, -1.99398550e-16, -2.39822029e-16,
        -2.78100175e-15,  1.00000000e+00]])

### Pseudorandom Number Generation

In [68]:
samples = np.random.normal(size=(4,4))
samples

array([[-0.22272462,  0.63469406, -0.40423339, -0.65965756],
       [-0.08472536,  0.52073238,  0.60678083, -0.05704837],
       [ 0.41849289,  1.14804255,  1.17698131,  0.58534763],
       [ 0.11478178, -0.11168922, -0.33743189, -0.46878779]])